### ISSUE TITLE
Sinatra::Application and Sinatra::Base return different environment

### ISSUE THREAD

**Issue by paralleltree** [sinatra/sinatra#1104]
Hi there.
I was in trouble about getting current environment with sinatra v1.4.7 and ruby 2.3.0.

I write following script to detect detail of the problem.

```ruby
# app.rb
require 'sinatra'
get '/' do
  [
    "Sinatra::Base.environment",
    "Sinatra::Application.environment"
  ].map { |e| "#{e}: #{eval e}" }.join("\n")
end
```

Then, I execute:

    $ ruby app.rb -e production

Finally, I get response from `localhost:4567` below:

```
Sinatra::Base.environment: development
Sinatra::Application.environment: production
```

But executing app.rb by following command,

    $ RACK_ENV=production ruby app.rb

it returns below:

```
Sinatra::Base.environment: production
Sinatra::Application.environment: production
```

That is to say, using first execution command and `Sinatra::Base.environment`, I couldn't get correct environment.
I may think wrong. Is it correct behavior?

**Comment by kgrz** [comment]
This is expected behaviour because the command line argument parsing functionality is limited to the [Classic style](https://github.com/sinatra/sinatra#modular-vs-classic-style) of Sinatra apps. If you were to use `Sinatra::Base`, then the environment has to be explicitly set using the `set ` helper or via `RACK_ENV`, which is why in the second run the environment gets reported as `:production`. In the classic style, the call to `set :environment` [happens automatically during the script initialization](https://github.com/sinatra/sinatra/blob/master/lib/sinatra/main.rb#L18).

This is the style for using `Sinatra::Base`:

```ruby
# app.rb
class App < Sinatra::Base
  set :environment, 'production'

  get '/' do
    puts settings.environment
  end
end

App.run!
```

```
ruby app.rb
```

You could skip the call to `set :environment` above if the `RACK_ENV` gets specified.

**Comment by paralleltree** [comment]
Thank you for your quick reply and I'm sorry for taking your time.
My problem is completely solved.

**Comment by kgrz** [comment]
No worries. Feel free to open issues if you need clarification about anything else. Sometimes bugs do get discovered that way.
