### ISSUE TITLE
Compromising via `uri` helper

### ISSUE THREAD

**Issue by gentoid** [sinatra/sinatra#1105]
#### Versions of apps:
- Sinatra 1.4.7
- Ruby 2.2.4

#### Problem:
It's very simple to substitute real hostname with malicious one via `uri` helper

#### Steps to reproduce:
- write Silm template with `uri` helper, let it be, e.g., `img src=url('/images/logo.gvg')`
- run Sinatra
- make a request with `curl`: `curl -v --header "Host: hey-man:3456" http://localhost`

#### What I'm getting:
curl shows me `<img src="http://hey-man:3456/images/logo.gvg" />`

#### What I'm expecting to see:
Either one of:
- my real hostname, don't know how, but it supposed to be used for that, right?
- see a text in the documentation, that it's very dangerous to do so because of - see what's I'm getting

#### References:
[/lib/sinatra/base.rb:271](https://github.com/sinatra/sinatra/blob/master/lib/sinatra/base.rb#L271) definition of the `uri` method

**Comment by rennhak** [comment]
+1

**Comment by zzak** [comment]
I'm not convinced this is a bug, simply passing the `Host` header to the server should be done by the HTTP client anyways. This is important in order to support proxies, automatic redirect, etc.

In any case, an attacker could only exploit this if there was a mitm and in this case there are worse things they can do then change the request host.

Thank you for your report!

**Comment by kgrz** [comment]
For future reference, please send any security related patches/bugs over email. https://github.com/sinatra/sinatra/blob/master/SECURITY.md has some details.
