### ISSUE TITLE
Add trailing slash at the end of the URL

### ISSUE THREAD

**Issue by tejasbubane** [sinatra/sinatra#1107]
Sinatra does not add trailing slash at the end of the URL.
This came up in https://github.com/exercism/exercism.io/issues/2780 where `/languages` was working fine but `/languages/` was returning a `404`.
Adding this issue as per @kgrz's suggestion.

**Comment by canton7** [comment]
Should it? Those are different paths - I don't know of any other server which would consider them to be the same...

**Comment by kgrz** [comment]
I hate to give this over-used example, but: Rails does it.

I understand that the underlying handlers treat the two URLs differently but the general practice I see is that, based on the situation, a webmaster would add redirect rules from one to the other. For instance: `https://dev.twitter.com/overview/documentation/`. If you visit that link in a browser, there's a 301 redirect to the non-trailing slash URL. (Although, a similar GET request in Rails would not result in a redirect, but would render the template for that action)

I'm totally okay with treating both URLs differently, but should we have a configuration item—which will be 'off' by default—somewhere which would treat them the same at Sinatra level? This might reduce a lot of the `/?`s in  `get '/location/?'`. If we don't go down that way, we can add this quirk in the documentation.

**Comment by beechnut** [comment]
I just spent about half an hour trying to debug why my URLs weren't working, and it turned out to be the trailing slash issue. I'm coming from mostly working on Rails projects, and while I've done Sinatra before, this is the first time I've run into this that I can recall.

The idea of the "sensible default" recommends that the default behavior of something that isn't explicitly configured defaults to a general idea of what should happen. Of course, _should_ is a value judgment that must be decided on by people. 

Perhaps it's the Rails background, but doing my best to put that aside, I can't think of a reason why I would expect a path ending in a trailing slash to be considered different from a path without. That (admittedly erroneous) assumption caused me to waste half an hour in front of a client trying to figure out what was wrong. That, I would argue, is not a sensible default.

My opinion is that Sinatra, going forward, should default to the optional trailing slash, and that there be an option like `set :strict_paths, true`, which triggers the current default behavior.

**Comment by zzak** [comment]
It's true that these **are** different paths, and consistent expected Sinatra behavior. However there is no test or spec which covers this, which is probably bad.

That said, just because Rails provides this convenience doesn't mean we should. Rails does this to provide a resourceful router, along with RESTful design, so it can assume that `/photos` and `/photos/` are the same resource and should dispatch to `#index`.

However, this is **not** in the current design of Sinatra or it's router.

If there's anything to be done here, it's documentation to make this more explicit. In my opinion it's not worth hacking in a setting just to allow this convenience and make the router that much more complicated.

**Comment by zzak** [comment]
After considering this again, anyone who is willing to write the patch (and tests).

I will accept adding an option for `:strict_paths` which defaults to true.

/cc @tejasbubane @kgrz @canton7 @beechnut #1216

**Comment by b264** [comment]
I think django actually sends back the one without the trailing slash as a redirect.  So for the "because Rails does it", we can examine other ways too... and pick the best
`/foo` => HTTP 301 to `/foo/`

**Comment by mwpastore** [comment]
WordPress does the same.

**Comment by zzak** [comment]
By all means, patches please. :angel:

**Comment by zzak** [comment]
Resolved by #1273

**Comment by snuggs** [comment]
> I can't think of a reason why I would expect a path ending in a trailing slash to be considered different from a path without. @beechnut 

[I've left ample examples and (spec) references from around the web](https://github.com/fastlane/ci/issues/15#issuecomment-373597905) to give some background on why (to @zzak's point) `/foo` & `/foo/` **ARE** indeed two different urls (and resources for that matter).

> This might reduce a lot of the /?s in get '/location/?' @kgrz 
That's actually an anti-pattern. One of those [That's just the way we've always done things around here](https://user-images.githubusercontent.com/38223/37504587-cb14f666-28b5-11e8-9aa4-35533736ea48.png) situations. 

`301` redirect and `<link rel=canonical...>` are 💯 . Anything else would be considered an anti-pattern as far as the web is concerned.
