### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by b264** [sinatra/sinatra#1123]
Is there any way to cut a new release off `master`?

Rails5 is almost done and there is no version that is compatible yet, but the `master` branch seems to be fine due to a couple things that were fixed since January.  Using Rails, Sidekiq, and Sinatra (for the Sidekiq administration) is a common paradigm.

**Comment by zzak** [comment]
There will be a release as soon as I can, until then feel free to use master.

**Comment by b264** [comment]
A `2.0.0-beta1` release that `bundle update` can upgrade would be better than folks using a commit sha on master or their own fork, in my opinion.  The beta would imply it's not done yet while still allowing a successful gemfile resolution by bundler.

**Comment by zzak** [comment]
I will consider cutting a pre-release, thanks.

**Comment by b264** [comment]
https://github.com/sinatra/sinatra/issues/1124

**Comment by b264** [comment]
https://github.com/sinatra/sinatra/issues/1115

**Comment by b264** [comment]
https://github.com/sinatra/sinatra/issues/1071

**Comment by b264** [comment]
https://github.com/sinatra/sinatra/issues/1117

**Comment by ericboehs** [comment]
@zzak thoughts on cutting a pre-release?

**Comment by zzak** [comment]
@ericboehs Thanks, I'm still considering

**Comment by zzak** [comment]
For anyone coming back to this, the reason for not releasing yet is because I'm waiting to merge stable `sinatra-contrib` and `rack-protection` gems into the repo.

However, there is a [blocking release](https://github.com/sinatra/sinatra-contrib/issues?q=is%3Aissue+is%3Aopen+label%3A%22blocking+release%22) on contrib and working through the remaining issues before I can do that.

Any help there is appreciated to speed up the release :bow:

No, I don't think I want to release before that is done, even a pre-release because [I explicitly said](http://zzak.io/log/2016-04-18-the-road-to-sinatra-2.0.html) that sinatra-contrib will be a first-class citizen.

Sorry for the delay, but you're free to use master until that work is done.

If you run into any issues please report them, but I'm not going to consider a release only to change one line in your Gemfile.
