### ISSUE TITLE
Sinatra::Streaming missing features

### ISSUE THREAD

**Issue by zzak** [sinatra/sinatra#1140]
This ticket is copied from sinatra/sinatra-contrib#178

**Comment by dentarg** [comment]
> This ticket is copied from [sinatra/sinatra-contrib#178](https://github.com/sinatra/sinatra-contrib/issues/178)

That issue says "Streaming getting buffered by Ruby" – I don't think this issue is with Sinatra, instead it is something addressed in the web server.

There was this recent issue with Puma 6 https://github.com/puma/puma/issues/3000 where the stream was buffered but that has been resolved.

Then there's this new way of doing streaming with Rack 3, "callable body" https://github.com/rack/rack/pull/1745, is this what this issue should be about, or should we close this?

**Comment by jkowens** [comment]
@dentarg I'd vote to close this issue. It's old and vague.

**Comment by zzak** [comment]
@jkowens Yeah that's my bad, this meant to be a place to collect streaming related issues but never got around to it 😭

**Comment by jkowens** [comment]
@zzak no worries 😂
