### ISSUE TITLE
Sinatra::RespondWith providing mime_type and Accept header

### ISSUE THREAD

**Issue by zzak** [sinatra/sinatra#1141]
This ticket is copied from sinatra/sinatra-contrib#149

**Comment by JonMidhir** [comment]
Have investigated this and I can only reproduce one of the two bugs now.

- When passing the header `application/rss+xml` the `/comics/:name/feed` route will indeed 404. 

- When visiting `/comics/:name/rss10` it's possible the 406 was actually a template engine error and fixed by this commit: https://github.com/sinatra/sinatra/commit/de8ebedbdc53bc4e58526377e55643162789ff34. Now it will 500 instead :)

I can take this and work on a fix if it's still useful. I guess there are two ways to go about it though, `mime_type` could take additional options for version etc. Or these can simply be parsed out of the string later.

**Comment by zzak** [comment]
@johnvoloski So we can close this ticket? :grimacing:
