### ISSUE TITLE
Can't get Sinatra::ConfigFile to work, always returns []

### ISSUE THREAD

**Issue by gonace** [sinatra/sinatra#1193]
Hi 
I've been struggling with Sinatra::ConfigFile and giving up so many times to get it to work and never have found a solution.

I'm running a simple Sinatra application that now need a config file with a base url.

Here is my BaseController:

```
class BaseController < Sinatra::Base
  register Sinatra::ConfigFile
  register Sinatra::Flash
  register Sinatra::Partial

  enable :sessions
  set :environments, %w{development test production stage}

  env = ENV['RACK_ENV'] || 'development'
  config_file "config/#{env}.config.yml"

  file = File.open("config/#{env}.config.yml", 'rb')

  puts '#################'
  puts '###   DEBUG   ###'
  puts '#################'
  pp file.read
  puts env
  p config_file
  puts settings.inspect
  puts '#################'
end
```

But the config_file is always []:

```
14:33:18 app.1  | #################
14:33:18 app.1  | ###   DEBUG   ###
14:33:18 app.1  | #################
14:33:18 app.1  | "development:\n  foo: development\n  bar: bar\ntest:\n  foo: test\n  bar: bar\nproduction:\n  foo: production\n  bar: bar"
14:33:18 app.1  | production
14:33:18 app.1  | []
14:33:19 app.1  | BaseController
14:33:19 app.1  | #################
```

I've tested adding the example in the documentation to the actual application class with the same result.

Anyone that have an idea?

**Comment by rennex** [comment]
According to the docs at http://www.sinatrarb.com/contrib/config_file.html you read the values by calling `settings.foo` and `settings.bar`.

`config_file` is a method call, and you're calling it a second time without arguments when you `p config_file`. But I'm not sure if that clears away the old settings.

**Comment by gonace** [comment]
Hi
I've removed that line you're reffering to but if I try to
`puts settings.fo`

I get 
`/Users/gonace/Development/Tulo/mittmedia-shop-url-resolver/controllers/BaseController.rb:17:in `block in <class:BaseController>': undefined method `foo' for BaseController:Class (NoMethodError)`

**Comment by rennex** [comment]
Then in that case, the configuration file you're loading doesn't include a "foo" setting under the current environment. I copy-pasted your example and put the configuration data in config/development.config.yml, and `settings.foo` works just fine. But calling `settings.foo2` gives me "undefined method `foo2' for BaseController:Class (NoMethodError)" because "foo2" isn't defined in that yml file.

Are you perhaps editing a different config file than what your code is loading? Or it doesn't have the heading corresponding to the current environment (production in your example)? Note that since you already have different environment configs in separate files, you should remove those "development:" and "production:" headings from the yml and just include the actual settings themselves.

**Comment by gonace** [comment]
Strange, the file is loaded and printed and as you can see there are a "foo". I have only one config file since I stubbed up a project with Sinatra just to test.

**Comment by rennex** [comment]
Well, either you're doing something wrong or your gems are somehow broken. Here's a minimal self-contained example that works for me. Contents of `config.yml`:

    foo: foobar

Contents of `foo.rb`:

    require "sinatra/base"
    require "sinatra/config_file"
    
    class BaseController < Sinatra::Base
      register Sinatra::ConfigFile
    
      config_file "config.yml"
      puts settings.foo
    end

Now when I do `ruby foo.rb` it prints:

    foobar

**Comment by gonace** [comment]
Hi
Sorry for a late response, I manage to install a virtual machine and I got it to work. It seams there are something wrong with my dev setup.
