### ISSUE TITLE
Exceptions not raised or handled if status 400

### ISSUE THREAD

**Issue by mwpastore** [sinatra/sinatra#1211]
`handle_exception!` calls `halt` if the status code is 400, circumventing `:raise_errors` and error handlers. This is definitely surprising behavior! Can we wait to call `halt` until after the other exit pathways are exhausted?

**Comment by jkowens** [comment]
I feel like I should respond since I was responsible for adding that behavior 😇 

The reason I chose to have it halt is because a 400 status means that the request is malformed, so it seemed to me the safest option is to just stop and let the http status communicate the problem. 

If the request continues, further exceptions could be encountered that hide the real issue. For instance, the `show_exceptions` template dumps the request `GET` and `POST` key/value pairs. If those parameters are malformed, the method that parses them will raise an error that results in a 500 status.

I'm just explaining the reason behind the decision, it may or may not be valid. Or there may be a better solution...hopefully this helps!

**Comment by mwpastore** [comment]
Thank you for responding! 

I think I understand what you're hoping to accomplish—or rather, hoping to avoid. My concern is that Sinatra provides a contract that allows developers to decide, on an application-by-application and environment-by-environment basis, whether to:

1. Show classy error pages
1. Catch and handle exceptions (e.g. build and respond with a JSON error object)
1. Bubble exceptions up to a middleware

If you're primarily concerned about the first pathway, there's no reason to disable the other two. Also, if you're only concerned about *part* of the first pathway being problematic, there's no reason to disable it entirely. Would you please take a look at [this commit](https://github.com/mwpastore/sinatra/commit/b3d4e385d5e046924478e0b072f1cecc8be7a455?w=1) and let me know your thoughts?

**Comment by jkowens** [comment]
That makes sense, I like what you have done with that commit 👍

**Comment by mwpastore** [comment]
Okay, I'll add a new test and submit a PR. Thanks Jordan!

**Comment by zzak** [comment]
Looking forward to a PR, thank you @mwpastore!

**Comment by mwpastore** [comment]
@zzak #1212 should do the trick!
