### ISSUE TITLE
sinatra 2.0.0.beta2 fork will cause unexpected shutdown

### ISSUE THREAD

**Issue by roroco** [sinatra/sinatra#1229]
here is my code:

```
require 'sinatra/base'

class C < Sinatra::Base
  get "/" do
    pid = fork do

    end
  end
end

C.start!
```

when I start this app and `curl localhost:4567`, the sinatra app output:

```
Fast Debugger (ruby-debug-ide 0.6.0, debase 0.2.1, file filtering is supported) listens on 0.0.0.0:42412
[2017-01-03 17:16:49] INFO  WEBrick 1.3.1
[2017-01-03 17:16:49] INFO  ruby 2.3.3 (2016-11-21) [x86_64-linux]
== Sinatra (v2.0.0.beta2) has taken the stage on 4567 for development with backup from WEBrick
[2017-01-03 17:16:49] INFO  WEBrick::HTTPServer#start: pid=11256 port=4567
Fast Debugger (ruby-debug-ide 0.6.0, debase 0.2.1, file filtering is supported) listens on 0.0.0.0:43257
== Sinatra has ended his set (crowd applauds)
127.0.0.1 - - [03/Jan/2017:17:16:59 CST] "GET / HTTP/1.1" 11311 0
[2017-01-03 17:16:59] INFO  going to shutdown ...
- -> /
[2017-01-03 17:16:59] INFO  WEBrick::HTTPServer#start done.
== Sinatra has ended his set (crowd applauds)
```

my env
```
roroco@roroco ~/Dropbox/rbs/ro_wemedia $ ruby -v
ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-linux]
roroco@roroco ~/Dropbox/rbs/ro_wemedia $ lsb_release  -a
No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 18 Sarah
Release:	18
Codename:	sarah

```

**Comment by mwpastore** [comment]
The problem is that the forked process inherits Sinatra's `at_exit` hook, which unfortunately shuts down the server when the forked process exits. Since you're already writing a modular application, the simplest solution is to run your application through a rackup script (i.e. config.ru) instead of using `run!` or `start!`. I believe this makes it so that `running?` isn't `true` and thus `quit!` doesn't fire the shutdown logic (either that or rackup or the application server becomes responsible for handling traps and avoids Sinatra's `at_exit` hook entirely, that would be interesting to investigate). There are some other options documented in [this](http://stackoverflow.com/a/38934866/1021515) excellent answer on StackOverflow.

I feel compelled to say that it's probably a bad idea to be forking processes from a route in any language, especially if the application is public-facing. If the logic is all Ruby logic, and not CPU-bound, [Threads](http://ruby-doc.org/core-2.4.0/Thread.html) might be a better fit; and if you are doing any significant amount of background processing, it may be worth exploring something like [Resque](https://github.com/resque/resque) or [Sidekiq](http://sidekiq.org). If you absolutely, positively need a forking route listening on a public IP address, make sure to rate-limit requests!
