### ISSUE TITLE
1.4.x stable release

### ISSUE THREAD

**Issue by zzak** [sinatra/sinatra#1231]
Tag issues/PRs to consider for stable release

**Comment by myronmarston** [comment]
FWIW, I'd be happy with a 1.4.x release that just includes the fix for the `::Fixnum` deprecation in Ruby 2.4.  Any idea on an ETA for the release?  I'm waiting to upgrade our [RSpec 3 book](https://www.amazon.com/Effective-Testing-RSpec-Build-Confidence/dp/1680501984/ref=sr_1_1?s=books&ie=UTF8&qid=1484252134&sr=1-1&keywords=rspec+3) to Ruby 2.4 (which we want to do before it is released) until there's a version of sinatra we can use that avoids the warnings.

**Comment by mwpastore** [comment]
@myronmarston Sinatra 2.0 will be released soon, and it will meet your requirements.

**Comment by myronmarston** [comment]
> @myronmarston Sinatra 2.0 will be released soon, and it will meet your requirements.

Good to know!  Does "soon" mean "sometime in January"?

**Comment by mwpastore** [comment]
"Soon" means "when it's ready," but even a casual observer of this repo should be able to discern that there has been a concerted effort over the past few weeks to ship it in as short a time frame as possible.

**Comment by b264** [comment]
As one of the specified "casual observers" I can confirm that

**Comment by zzak** [comment]
Hey ya'll,

If you find any issues that would be good candidate for a stable release, please tag them here.

I don't want to fill this thread with conversation about 2.0 -- because there may be some legitimate reason to ship a stable version as well.

Please stay on track <3 We can do this!

**Comment by charliesome** [comment]
Hey @zzak - given that there haven't been any other suggestions for stable backports since this issue was opened, would it be possible to release 1.4.8 with just the `Fixnum` change?

We're currently pegging to a manually-built prerelease version of Sinatra at https://github.com/charliesome/sinatra/commit/b2a590cc1c6a96c880da682ac3ba73a508e5cb7b, but it would be nice to be able to switch back to an official stable release as soon as one's available.

**Comment by zzak** [comment]
So I just spent some time trying to get stable green and ran into soo many dependency issues between all of the supported versions.. :sob:.

This [is as close as I could get](https://travis-ci.org/sinatra/sinatra/builds/192354663).

**Comment by mwpastore** [comment]
I'm not having much more luck on my fork. I just sat down to look at it again for the first time since Friday, so I'll see how far I can get. I may steal some things from your branch. 😛

**Comment by jkowens** [comment]
@mwpastore nokogiri is probably what is giving you trouble with mini_portile2. I think if you pin to nokogiri 1.6.8.1 for Ruby version < 2.1.0 you'll be ok.

**Comment by myronmarston** [comment]
As an open source maintainer, I know how important it is to get the build green on all versions you support.  But it might be worth considering releasing 1.4.7 simply as 1.4.6 + the `Fixnum` warning fix, even if the build isn't quite green on all ruby versions you support--particularly if the failure has to do with incompatible gems, and not a failure of Sinatra's test suite. It looks like the build is green on 1.8.7 and on 2.1+, so the likelihood of it being broken on 1.9 and 2.0 due to the Fixnum change (if it is the only change from 1.4.6) seems very minimal.

**Comment by zzak** [comment]
@myronmarston Oh, the build has been green, I will try to cut a stable release next week.

**Comment by zzak** [comment]
:clapper: https://rubygems.org/gems/sinatra/versions/1.4.8 :clapper:
