### ISSUE TITLE
skip session option for static files

### ISSUE THREAD

**Issue by dvh91** [sinatra/sinatra#1241]
I'm using `Rack::Session::Couchbase` for session management.
all static files are under public folder (the default of Sinatra)
every request to static file goes all the way to couchbase to gets the session document.

Is there a way to intercept all static file request with 'before' so I'll make the request skip the session
`request.session_options[:skip] = true`

**Comment by mwpastore** [comment]
Are you `use`-ing Rack::Session::Couchbase in config.ru or within your Sinatra app?

**Comment by dvh91** [comment]
@mwpastore in Sinatra app

**Comment by mwpastore** [comment]
So this is a bit tricky because of the way Rack middleware works. Basically, Rack::Session does its thing when it sees the `rack.session` cookie before Sinatra even sees the request, so it doesn't have a chance to decide whether skip it or not. Fortunately, you have a two options:

1. Serve static assets from outside Ruby, i.e. in your NGINX or Apache (or what have you) configuration. This is probably the most common pattern as e.g. NGINX can serve static assets much faster than Ruby. You'd then reverse proxy any requests for dynamic content to the Ruby app server. 

1. If putting a reverse proxy in front of your Ruby app server isn't feasible for some reason, the next best option is to simply insert the [Rack::Static](http://www.rubydoc.info/github/rack/rack/Rack/Static) middleware into your app *before* Rack::Session. Rack::Static will intercept requests for static assets and serve them, and pass any remaining requests "upstream" to be serviced by Sinatra. 

    ```ruby
    use Rack::Static, :urls=>%w[/css /images /js], :root=>'public'
    use Rack::Session::Couchbase
    ```

    (n.b. that this won't work with Sinatra's built-in sessions, i.e. `enable :sessions`, due to the way it loads its middleware stack. To use Rack::Static with Sinatra under these circumstances, you'll need to `use` it in rackup script, e.g. config.ru, before `run`-ing your application.)

**Comment by dvh91** [comment]
@mwpastore - thanks for your reply. I took the second approach but something pretty weird is happening.
I've put breakpoints in both initialize functions of CB middleware and in Static middleware.

For some reason, the first to fall into the breakpoint is the CB.
In config.ru I used the Static middleware first and then the CB. just like you mentioned.

Also, I noticed that in rack's builder.rb `use` method, where it should get all middlewares, it gets the Static middleware first and then the CB as expected. but for some reason it initialize it in the different order.

**Comment by mwpastore** [comment]
Yes, that makes sense. Consider this example:

```ruby
use Foo
use Bar
run Qux
```

Based on a quick peek at the code, I think Rack::Builder does something like this:

```ruby
a = Qux.new
b = Bar.new(a)
c = Foo.new(b) 
```

As Rack receives requests, it fires `c.call(env)`, and the request passes up the chain.

**Comment by dvh91** [comment]
@mwpastore - replaced the order. it does make the change.
but unfortunately the initial problem still occurs - CB set_session gets called when static file served.

**Comment by mwpastore** [comment]
How have you configured Rack::Static? What static files are you trying to
serve?

**Comment by dvh91** [comment]
@mwpastore 
```
use Rack::Session::Couchbase, :path => '/', SOME_MORE_CONFIGURATIONS...
use Rack::Static, :urls=>["/styles", "/img", "/fonts", "/js"], :root=>'public'
```

**Comment by mwpastore** [comment]
Rack::Static has to come first. What is the path to the static file you're testing with?
