### ISSUE TITLE
Routes added in extension are not available after reload

### ISSUE THREAD

**Issue by raldred** [sinatra/sinatra#1280]
I'm was hoping to use the extensions to separate up routes in my modular application.
I'm hitting an issue with the reloader extension.

When changes are made to one of my extensions that provides some routes, those routes are not longer available after saving, sinatra return 404. A full boot of the app brings them back.

The routes are added inside `self.registered(app)`

Any changes to the routes in the base application take effect. However it's like the extension is never re-registered after changes are saved.

```
class Leads < Sinatra::Base
  register Sinatra::ViewingFeedbackController

  get '/leads/:id' do

  end

end
```

```
module Sinatra
  module ViewingFeedbackController

    module Helpers

    end

    def self.registered(app)
      app.helpers ViewingFeedbackController::Helpers

      app.post '/leads/:lead_id/viewing_feedback' do

      end

      app.patch '/leads/:lead_id/viewing_feedback/:id' do

      end
    end
end
```

**Comment by murdho** [comment]
Hey @raldred, do you still have the issue with Sinatra 2.0 release? I couldn't reproduce the issue with version 2.0.

Could you also verify that are you registering the `Sinatra::Reloader` before your extensions? Since reloader overrides some `Sinatra::Base` methods, it might be that the first time the extension is registered without the overrides and that seems to trigger some unwanted behaviour.

**Comment by arbales** [comment]
I also had this problem — I was able to resolve it partially, but now the contents of my routes aren't updating. Using v2.0.

**Comment by raldred** [comment]
Hey sorry for late reply. I have configure blocks defined where
Sinatra::Reloader is setup. Im pretty sure the extensions are loaded in
after that. I'll double-check​ later.

**Comment by arbales** [comment]
@raldred are you also using `Sinatra::Extension`?

**Comment by zzak** [comment]
While I'm not entirely sure, I _think_ this sounds related to how Mustermann compiles routes when they are defined.

**Comment by Ice-Storm** [comment]
I didn't meet the same problem when I run your code with Sinatra 2.0, except missing the code `Leads.run!`.

**Comment by namusyaka** [comment]
@raldred Sorry for the late reply.
For investigation of this problem, I need a minimal repository for reproduction (with Gemfile.lock).

**Comment by msyesyan** [comment]
![screen shot 2018-09-25 at 15 54 12](https://user-images.githubusercontent.com/2162116/46000487-49016880-c0db-11e8-927e-b15db83d90ff.png)

I got this error after change my extension code. 

By the way, the first time I run `rack` works,

**Comment by msyesyan** [comment]
https://github.com/msyesyan/sinatra-reloader-extension-error  here is a demo app

ruby version is 2.5.1

**Comment by msyesyan** [comment]
@raldred please have a look ^_^

**Comment by daBee** [comment]
Not sure if this is related, but I have a view that's not visible.  `:development` environment.  

    Errno::ENOENT - No such file or directory @ rb_sysopen - /Users/rich/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/sinatra-contrib-2.0.5/lib/sinatra/views/shorts/about.erb

__note:__ `/tmp/Xalways_restart.txt` is not forcing restart (hence the 'X').  My goal is to have erb files reload upon resave in `:production`, or a route.  

__note 2:__ I've seen references from way back (0.92) that Sinatra dropped support for `Sinatra::Reloader` due to the complexity, but the documentation has no reference to any of this.  So I am to assume this is expected to be a valid extension.  Just to be clear.

**Comment by ankitsinghaniyaz** [comment]
My site fails to reload when there's an error. Any idea what could be wrong?

**Comment by daBee** [comment]
What does the error say?  Check your nginx or apache log.
