### ISSUE TITLE
examples/chat.rb doesn't work on Heroku anymore

### ISSUE THREAD

**Issue by rajsahae** [sinatra/sinatra#1334]
I think it once worked, I see in the origin gist (https://gist.github.com/rkh/1476463) heroku working is specifically mentioned.

I based a small project on this and uploaded it to heroku recently and things weren't working. I reverted to the original version and it still doesn't work. When you attempt to submit text, it takes you back to the login page. Any ideas?

Here is a sample app: https://eug-markov-bot.herokuapp.com/

**Comment by jkowens** [comment]
I think you just need to update this line: https://gist.github.com/rkh/1476463#file-chat-rb-L29

to use the https protocol:

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script> 

Another comment suggested you might need to use jQuery 1.8 specifically due to an API change:

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js"></script>

**Comment by rajsahae** [comment]
Yeah, switching to https protocol fixes it.
