### ISSUE TITLE
markdown function only works for files with the .markdown extension

### ISSUE THREAD

**Issue by ghost** [sinatra/sinatra#1440]
```ruby
markdown :index
```

only checks for `views/index.markdown`, and not `views/index.md` or `views/index.mkd`. The docs suggest that all three should work. (Both the [README](http://sinatrarb.com/intro.html) and [cookbook entry](http://recipes.sinatrarb.com/p/views/markdown) state this.)

**Comment by priscilasolis** [comment]
Taking...

**Comment by priscilasolis** [comment]
I did what this issue said and found that, like you mentioned, `views/index.markdown` worked, and `views/index.md` or `views/index.mkd` did not. I tried to find the root cause of this issue without much success.
At one point though, I don't know if I typed in some command, or what caused the change, but I tried it again and it did work. 

Could you try again and see if you still have this issue?

**Comment by ybden** [comment]
Tried again, same issue. All dependencies were fully up-to-date (sinatra 2.0.1, tilt 2.0.8).

Here's a minimal testcase that reproduces the issue:

```ruby
# test.rb
require 'sinatra'

get '/' do
  markdown :index
end
```

Then, create `views/index.md` as before (content obviously doesn't matter, I just put a line of text in there).

Finally, run `ruby test.rb` and go to http://localhost:4567.

Hopefully you should be able to reproduce with this!

**Comment by priscilasolis** [comment]
I was using Sinatra 2.0.2 and changed to the 2.0.1 version you are using, but it still works. I'm not sure what the issue could be and it's specially confusing since it didn't work for me either when I tested it out in the beginning.

**Comment by kgrz** [comment]
Are you adding the `require 'rdiscount'` line in your apps? I've checked this with `2.0.3`, and `.md` works. My gemfile.lock:

```
GEM
  remote: https://rubygems.org/
  specs:
    mustermann (1.0.2)
    rack (2.0.5)
    rack-protection (2.0.3)
      rack
    rdiscount (2.2.0.1)
    sinatra (2.0.3)
      mustermann (~> 1.0)
      rack (~> 2.0)
      rack-protection (= 2.0.3)
      tilt (~> 2.0)
    tilt (2.0.8)

PLATFORMS
  ruby

DEPENDENCIES
  rdiscount
  sinatra (~> 2.0)

BUNDLED WITH
   1.16.1
```

**Comment by ybden** [comment]
So, from a fresh install of sinatra (2.0.3), no rdiscount, sinatra complains initially about ruby-pandoc missing. After installing rdiscount, I get the same error as previously:

```
Errno::ENOENT at /
No such file or directory @ rb_sysopen - /tmp/test/views/index.markdown
```

This means that sinatra is clearly picking up the existence of rdiscount. Adding `require 'rdiscount'` (either before or after the `require 'sinatra'` line) makes no difference, I still get the same error. I'm not really sure what could be going on here. This is a plain ruby install (2.4.2) with only the sinatra, rdiscount and http gems installed.

**Comment by dentarg** [comment]
@ybden do you mind putting all the code to reproduce in a repo on github? it would help debugging the issue and making sure we are testing the same things

also, are you using bundler?

**Comment by ybden** [comment]
Okay, so several points to make here:
- I'm new to ruby, so hadn't been using bundler before. I've tried once but gave up after confusing/conflicting documentation (do I use `require 'bundler/setup'` and what does that do, or `bundle exec`, or do I need to use both, etc.)
- However, after spending some time today reading through more stuff on bundler I'm now fairly confident that I understand how to use it properly
- The error I was getting earlier with rdiscount was actually because I accidentally had the `index.md` in the project root, and not in `views` (whoops...). Doesn't exactly help that this is the same error I was getting previously, but oh well
- Since it was a while ago that I found this bug (was busy since then, sorry for the wait) and I'd wiped my `~/.gems`, I forgot that I actually had redcarpet installed. Kinda unfortunate, because:
- The bug occurs with redcarpet only. I tried out all the other tilt engines (rdiscount, redcarpet, bluecloth, kramdown, pandoc & maruku). Everything finds `index.md` successfully, with the exception of pandoc, which doesn't have a gem for some reason? and redcarpet, which gives the Errno::ENOENT I pasted a couple comments above
- I've set up [a test case](https://github.com/ybden/sinatra-test) which you can try by running `bundle exec ruby test.rb`

Sorry for the confusion regarding rdiscount as well as the wall of text. Hope this helps.

**Comment by ybden** [comment]
In other words: this bug occurs specifically when (and only when) using redcarpet.

**Comment by ybden** [comment]
Actually, it would appear that I missed out commonmarker. Just tried that, and it works fine as well.

**Comment by mig-hub** [comment]
I am using redcarpet and I have the same issue.

**Comment by jkowens** [comment]
This appears to be a Tilt issue. A workaround can be done like below:

```
# test.rb
require 'sinatra'
require 'tilt/redcarpet'

# If using redcarpet 2.0 or greater
Tilt.register Tilt::Redcarpet2Template, 'markdown', 'mkd', 'md'

get '/' do
  markdown :index
end
```

**Comment by jkowens** [comment]
Issue reported to Tilt. See rtomayko/tilt/issues/345.
