### ISSUE TITLE
Siantra 2.0.5 may throw "can't dup NilClass" in Ruby < 2.4

### ISSUE THREAD

**Issue by jeltz** [sinatra/sinatra#1514]
The c686a10be68a959c34495c4969dcbabe7b93205e commit introduced a bug in Ruby 2.2 and 2.3 since it failed to take into account that parameter values can be `nil` (e.g. for requests with paths like `/?x`) and that `NilClass#dup` throws `TypeError: can't dup NilClass` in older rubies (that change was introduced in https://github.com/ruby/ruby/commit/70d8e6cf22515bfbf15bd283726ce9b72730164d).

I think the solution is to just do something like `val && force_encoding(val.dup)` but I need to install Ruby 2.3 to check. I am pretty busy right now and do not know when i will find the time so feel free to write a patch.

**Comment by namusyaka** [comment]
Definitely bug and my bad...
Thanks for the report.

**Comment by stephenreay** [comment]
I've just come across this bug, 7 months after a fix for it was merged, because there's no newer release of Sinatra available to install.

I don't know what your usual release schedule is, but at this rate it's a 1 month delay for each extra character in the library.

Yes, I can get around it by installing a more recent version of Ruby, but when a client is using an LTS distro release, it's not always as simple as just "well update ruby".
