### ISSUE TITLE
Development 404 page still shows up when using `-e production` command-line flag

### ISSUE THREAD

**Issue by leafac** [sinatra/sinatra#1544]
Let `server.rb` be simply

```ruby
require "sinatra"
```

Now run it with

```console
$ ruby server.rb -e production
```

Sinatra will say that it’s running in production mode:

```console
== Sinatra (v2.0.5) has taken the stage on 4567 for production with backup from Thin
```

But visit <http://localhost:4567> and you’ll see the development 404 page:

<img width="508" alt="Screen Shot 2019-06-22 at 08 35 48" src="https://user-images.githubusercontent.com/586813/59964008-bf939100-94c8-11e9-9bbc-01f4e032ea45.png">

I tried this with both WEBrick and Thin.

Of course, the problem goes away when using the `APP_ENV` environment variable:

```console
$ env APP_ENV=production ruby server.rb
```

<img width="462" alt="Screen Shot 2019-06-22 at 08 37 23" src="https://user-images.githubusercontent.com/586813/59964023-f669a700-94c8-11e9-9478-0a7bf876dbb0.png">

**Comment by jkowens** [comment]
This is an interesting issue. It happens because this block is called before the command line options are parse and handled:

https://github.com/sinatra/sinatra/blob/eee711bce740d38a9a91aa6028688c9a6d74b23b/lib/sinatra/base.rb#L1835

Command line options are processed later here:

https://github.com/sinatra/sinatra/blob/eee711bce740d38a9a91aa6028688c9a6d74b23b/lib/sinatra/main.rb#L13

To fix this I think the `configure :development` call should be moved from `base.rb` to `main.rb`.

**Comment by leafac** [comment]
How do you think this problem should be solved?

**Comment by jkowens** [comment]
Good question, I tried a couple options and realized it isn’t as easy to fix as I hoped.  The issue is that classical apps extend Application which extends Base (where the configurations are originally made). So supporting both classic and modular style apps becomes tricky. If anyone has any ideas please chime in 🙂

**Comment by leafac** [comment]
Hmmm, what if we didn’t offer the command-line flag? It’s awkward that we have two ways of accomplishing the same thing, and it’s difficult to tell which should be preferred (the environment variable, it seems).

**Comment by jkowens** [comment]
That sounds like a valid option to me. I put together a PR #1547 for another possible solution.
