### ISSUE TITLE
Heads-up to dependents

### ISSUE THREAD

**Issue by namusyaka** [sinatra/sinatra#1557]
We're planning to change a lot of things in v3.0.0, probably we'll break some backward-compatibility at the same time.
We should cut some release candidates for the version, of course, but I guess it's not enough.

In order to reduce the number of people who suffer from large changes in v3.0.0, I believe that it's very effective to heads-up in advance to the major dependents.

**Comment by rubyFeedback** [comment]
IMO all continued efforts are great for the larger sinatra ecosystem. I use sinatra primarily because it is so much simpler and flexible, so I don't have to use or tap into the complexity of rails, padrino, hanami etc...

Being able to move forward is important for projects. I guess most people will find it easy to transition; perhaps the only ones that may be affected more, would be those with a larger sinatra code base in use, but I think this will be a minority nonetheless.
