### ISSUE TITLE
Support Namespace in Extensions through extends

### ISSUE THREAD

**Issue by jessebs** [sinatra/sinatra#1679]
There are multiple ways to implement extensions, one of which is a very modular approach by using extends, for example:

```ruby
// app.rb
require 'sinatra/base'
require_relative 'routes'
class App < Sinatra::Base
  register Routes
end

// routes.rb
require 'sinatra/extension'
module Routes
  extend Sinatra::Extension

  get '/example' do
    'example route'
  end
end
```

Unfortunately, this approach doesn't appear to support namespacing.  Adding `extend Sinatra::Namespace` to the Routes module and setting up a namespace results in a SystemStackError - stack level too deep error.

The namespacing documentation mentions the ability to use it with extensions by defining the registered method, but it doesn't look that that should be a requirement for implementing an extension and goes against the above paradigm - http://sinatrarb.com/extensions.html.

**Comment by namusyaka** [comment]
Thanks for the report.
First off, I would like to introduce a workaround for the stack level too deep error by adding `extend Sinatra::Namespace` to `App`, it would be something like:
```ruby
# app.rb
require 'sinatra/base'
require 'sinatra/namespace'
require_relative 'routes'
class App < Sinatra::Base
  extend Sinatra::Namespace
  namespace '/foo' do
    register Routes
  end
end

# routes.rb
require 'sinatra/extension'
module Routes
  extend Sinatra::Extension

  get '/example' do
    'example route'
  end
end
```

Next, a case you reported triggers the stack level too deep error indeed, and it should not be expected. Even If it does not work properly, we should use easy-to-understand error instead of that.

**Comment by dentarg** [comment]
This looks resolved to me.
