### ISSUE TITLE
XSS via Host Header Injection

### ISSUE THREAD

**Issue by theo0k** [sinatra/sinatra#1939]
I discovered two ways of Host Header Injection that lead to XSS:

1) By changing the `Host` header in the request.

2) Using the `X-Forwarded-Host` header.

Instead of a *uri*, we can pass an XSS payload in these headers like: `-->'"><script>alert()</script>`

https://github.com/sinatra/sinatra/blob/35bc85b18a4154a5bf94044460c992b58d65c964/lib/sinatra/base.rb#L1998

```curl
curl -X GET "https://127.0.0.1" \
     -H "Host: 127.0.0.1" \
     -H "X-Forwarded-Host: -->'"><script>alert()</script>"
```

![image](https://github.com/sinatra/sinatra/assets/37907733/169e092d-d407-48a0-b1e7-3780c64d4b32)

**Comment by dentarg** [comment]
Thanks for the report. Do you have any suggestions what to do about it?

**Comment by theo0k** [comment]
Hello @dentarg,

I initially suggest the HTML escaping within the url in this code snippet:

```html
<img src='#{uri '/__sinatra__/404.png'}'>
```

**Comment by dentarg** [comment]
Yeah, I was thinking that and `<img src='#{Rack::Utils.escape_html(uri('/__sinatra__/404.png'))}'>` does work fine.

I was also thinking, why do we need to use `uri` at all here? So I looked in the git history, and found https://github.com/sinatra/sinatra/commit/238eedeb52dbbf688d561751d9dd5ad79c59c6ff, the reason is "when running under a nested path"

...but why not use the same solution, [`SCRIPT_NAME`](https://github.com/rack/rack/blob/main/SPEC.rdoc#label-The+Environment), as for the 500 image? I did that in https://github.com/sinatra/sinatra/pull/1943

**Comment by theo0k** [comment]
Because by using the header `X-Forwarded-Host` we are able to change the Host Header and instead of a host, we write a Javascript payload.

**Comment by theo0k** [comment]
But yes, you can use the solution that you did in https://github.com/sinatra/sinatra/pull/1943
