### ISSUE TITLE
Remove the `IndifferentHash` initializer

### ISSUE THREAD

**Issue by dentarg** [sinatra/sinatra#1953]
From @jkowens in https://github.com/sinatra/sinatra/pull/1951

> Looking over the code, I'm not sure that the `initialize` method makes sense to me.
> 
https://github.com/sinatra/sinatra/blob/6ddd6b63bf91609369b0cfa1248aa9c50ead0921/lib/sinatra/indifferent_hash.rb#L46-L50
https://github.com/sinatra/sinatra/blob/6ddd6b63bf91609369b0cfa1248aa9c50ead0921/lib/sinatra/indifferent_hash.rb#L203-L212
>  
>  I don't know why you'd want to call `convert_value` on a value that's been specified as a default value when a key is missing. See https://ruby-doc.org/3.2.2/Hash.html#method-c-new
> 
> 
> ```
> h = Sinatra::IndifferentHash.new(a: 1)
> h[:b] = {"a" => 1 }
> ```
> 
> I'm thinking maybe that should be removed to eliminate possible confusion?

**Comment by olleolleolle** [comment]
Now, having re-read the description and example a few times, I also feel it's probably a mistake, a bug, introduced by confusing this API with something like https://api.rubyonrails.org/classes/ActiveModel/AttributeAssignment.html.

**Comment by olleolleolle** [comment]
So, I support removing.

**Comment by mwpastore** [comment]
Wow, what a mess. Sorry y'all. Looks like I was aiming to make it work like ActiveSupport::HashWithIndifferentAccess (i.e. initialize an indifferent hash with normalized entries) but maybe erroneously thought that Hash#initialize expects the same kind of argument (when it actually expects a default value object)? So as discussed in #1948 calling `super` is the wrong thing to do here; I should have either implemented initializing logic a la ActiveSupport::HashWithIndifferentAccess#initialize or simply omitted the initializer entirely. Since we already removed the misleading documentation for the former behavior I support removing the initalizer as well. 

Bad design, bad execution, bad documentation... again, my apologies.
