### ISSUE TITLE
Sinatra 1.3.2 adds 'non request' params to params objects with some routes

### ISSUE THREAD

**Issue by mattetti** [sinatra/sinatra#453]
When using routes such as: /users/:id 2 'non request' params get injected in the params object (captures and splat to be more exact). That broke by param verification code which is checking the params against specific rules.

Could you please consider moving these values from the params hash?

Thanks

**Comment by CloCkWeRX** [comment]
This or something very similar appears to have cropped up in  2.0.0 (params regularly contains 'captures' again); I'm unclear if it was intentional or a regression of this issue; and the only time its mentioned is in the changelog for 0.9.0(!) as being added in... which this bug disagrees with.

If its intended (http://www.sinatrarb.com/intro.html suggests yes); would it be possible to document in the changelog/readme?
