### ISSUE TITLE
routing logging to file

### ISSUE THREAD

**Issue by auxbuss** [sinatra/sinatra#484]
What is the canonical method for writing the sinatra log to a file?

Say I have the following:

```ruby
require "sinatra/base"

module App
  class Main < Sinatra::Base

    configure do
      enable :logging
    end

    before do
      logger.datetime_format = "%Y/%m/%d @ %H:%M:%S "
      logger.level = Logger::INFO
    end
  
    get '/' do
      logger.debug "debug message"
      logger.info "info message"
      "hello world"
    end
  end
end
```

I basically want to say, somewhere:

```ruby
logger = Logger.new('log/app.log', 5, 'weekly')
```

How do I do that?

**Comment by zzak** [comment]
I believe this can be worked around by using `custom_logger` as explained in this comment: https://github.com/sinatra/sinatra/issues/484#issuecomment-44174658

Since this has been released and works to solve this issue, I'm giving this ticket a close.

If anyone has some ideas how to make this experience better, please submit a patch :)

**Comment by diei** [comment]
If you use Passenger redirecting STDOUT to a file is not a good idea. It causes in my case that Passenger does not start: https://github.com/phusion/passenger/wiki/Debugging-application-startup-problems#stdout-redirection

**Comment by FranklinYu** [comment]
@zzak The `custom_logger` only modifies `logger` in request handler; logs produced by `Rack::CommonLogger` is still sent to STDERR.

@diei This duplicates the log from STDOUT to the file instead of redirection.
