### ISSUE TITLE
add hijack io support to streaming once spec is finalized

### ISSUE THREAD

**Issue by rkh** [sinatra/sinatra#604]
see rack/rack#481

**Comment by b-dean** [comment]
@rkh, whatever happened to this? Does the shim middleware exist somewhere that we can use it? on rack/rack#481 you mention that this will be in Sinatra 1.4, but that was a long time ago and I still don't see a way to use this with Sinatra's `stream` helper method (which is where I would expect it to show up).

I actually made sinatra/sinatra#1035 because I was having issues getting streams to work on puma. I'm guessing it's related to this (because puma just keeps closing my stream).

**Comment by dentarg** [comment]
Not sure we need or should add support for either full or partial hijack in Sinatra?

But adding support for/updating the streaming class to make use of "callable body" (https://github.com/rack/rack/pull/1745) could be something (but a new issue perhaps?).

**Comment by dentarg** [comment]
Created https://github.com/sinatra/sinatra/issues/1892, closing this one
