### ISSUE TITLE
Sinatra matches Accept headers too liberally

### ISSUE THREAD

**Issue by qwzybug** [sinatra/sinatra#866]
Noticed this when updating an older app of mine to a newer version of Sinatra: two routes with the same name providing different content types will be matched unpredictably, especially in requests sent by browsers, which frequently accept "\*/\*;q=0.8" on all requests. Sinatra will match this to the first route by that name defined in the file, even if there is another explicit route defined to match the higher-quality, explicit content type sent by the client.

Test case: https://github.com/qwzybug/sinatra/blob/accept_specificity/test/routing_test.rb#L1127

Makes it difficult to rely on provides: to distinguish routes with the same name.

**Comment by zzak** [comment]
I wonder if this is still true for mustermann.

**Comment by zzak** [comment]
Ah yes, I'm afraid this has little to do with mustermann and the situation is still the same.

Unfortunately, as @jeremyevans pointed out, the current implementation of Sinatra doesn't allow for re-prioritizing routes. We can only assume that the first route that matches wins, and otherwise have to work around this by hand (like the example Jeremy wrote).

In this case, I think we can close this ticket.

Open to patches to improve this, or at the very least documentation in-case there is any uncertainty about the current docs.

Thank you!
