### ISSUE TITLE
Thank you! Sinatra is great

### ISSUE THREAD

**Issue by BanzaiMan** [sinatra/sinatra#920]
I love Sinatra's approach to lean and mean web apps. You are great. You are doing a wonderful job!

Thank you! :heart: :heart: :heart:

**Comment by anthony-ng** [comment]
:thumbsup::thumbsup::thumbsup:

**Comment by nerdExpo** [comment]
Hooray!

**Comment by daluu** [comment]
+1

First I've seen on filing an issue to praise a project. And then having it tagged as "vulnerability", "regression", and "3rd party issue". Seems humorous to me.

**Comment by totzYuta** [comment]
How sweet you are! :beers:

**Comment by simon2k** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart: :)

**Comment by dariubs** [comment]
:heart: :heart: :tophat:  :heart: :heart:

**Comment by daluu** [comment]
Btw, I see sinatra (per the readme here on Github) has a Twitter page/account, a mailing list, IRC and Slack channel. Those seem to be more appropriate for offering praise than doing it here in a Github issue for bugs and enhancement requests, especially for those posting emoticons.

I hope this behavior doesn't go viral into other open source projects. Imagine the popularity of OSS projects based on the # of votes & emoticons in their Github issues instead of current means...

I mean, you folks don't seriously post such things in your organization's private bug trackers and Jira do you? LOL.

**Comment by zotherstupidguy** [comment]
@daluu i think someone called BanzaiMan can cheer as much as he wants :)) but ofcourse you are correct

**Comment by vcavallo** [comment]
This is wonderful, but I advocate closing this now.
